### ISSUE TITLE
Erro ao gravar registro

### ISSUE THREAD

**Issue by SoftPratico** [Jonas452/adianti_code_generator#1]
Está ocorrendo erro quando clica no botão "Salvar" no <Table>Form.class.php
Segue anexo uma sugestão para corrigir o problema.
Atenciosamente,
Alair

![image](https://user-images.githubusercontent.com/21366115/44544994-2cdc6700-a6ea-11e8-93f8-35f45d6ae215.png)

![image](https://user-images.githubusercontent.com/21366115/44545131-952b4880-a6ea-11e8-994e-d6fb00b7bbda.png)

[List.class.zip](https://github.com/Jonas452/adianti_code_generator/files/2315743/List.class.zip)

**Comment by Jonas452** [comment]
Olá, obrigado por reportar a issue. Na verdade esse erro não ocorre exatamente ao salvar o registro, e sim no momento de carregar o List (que vem após o salvar). Esse erro é devido essa classe TDatagridTables não existir no pacote do Adianti, é uma classe custom criada pela nossa equipe de TI do Ceres. A sua solução é sim viável para aquelas que não tem acesso a essa classe (TDatagridTables).
